import Link from "next/link";
import {CheckCircle2,Eye,HeartHandshake,MapPinned,MoonStar,Route,ShieldCheck} from "lucide-react";
import {SearchForm} from "@/components/search-form";
const benefits=[
 {icon:Route,title:"Live safer routing",detail:"Compare practical route alternatives"},
 {icon:MapPinned,title:"Community intelligence",detail:"Use available safety and road context"},
 {icon:HeartHandshake,title:"Trusted journeys",detail:"Share a route link and check in when needed"},
];
export default function Home(){return <div className="container"><section className="hero"><div className="hero-copy"><div className="eyebrow">Safety-aware navigation</div><h1>Your safer<br/>way home.</h1><p>Lunara compares live OpenStreetMap routes using available road context. Incident, lighting, activity, and live traffic data are not currently connected.</p><div className="hero-visual" aria-hidden="true"><div className="hero-moon"/><svg viewBox="0 0 480 160" preserveAspectRatio="none"><path className="hero-route-halo" d="M0 121 C82 118 99 27 190 61 S301 135 360 71 438 73 480 19"/><path className="hero-route-line" d="M0 121 C82 118 99 27 190 61 S301 135 360 71 438 73 480 19"/><circle cx="190" cy="61" r="7"/><circle cx="360" cy="71" r="7"/><circle cx="360" cy="71" r="3" className="hero-route-dot"/></svg><span className="hero-visual-caption">A little more clarity on every journey</span></div><div className="hero-benefits">{benefits.map(({icon:Icon,title,detail})=><div className="hero-benefit" key={title}><span className="hero-benefit-icon"><Icon size={18}/></span><span><strong>{title}</strong><small>{detail}</small></span></div>)}</div><div className="assurance"><span><CheckCircle2 size={16}/> Explainable scores</span><span><ShieldCheck size={16}/> Privacy-minded</span><span><MoonStar size={16}/> Time-aware</span></div></div><SearchForm/></section><section className="section"><div className="page-head"><div><div className="eyebrow">More context. Less uncertainty.</div><h2>Designed around your journey</h2></div><Link className="secondary" href="/report" style={{textDecoration:"none",display:"grid",placeContent:"center"}}>Report a concern</Link></div><div className="feature-grid"><article className="card feature"><MapPinned/><h3>Mapped corridors</h3><p>Compare live route geometry and road context. Estimates do not include real-time traffic or incidents.</p></article><article className="card feature"><Eye/><h3>Clear explanations</h3><p>See which available factors informed an estimate and which safety data is unavailable.</p></article><article className="card feature"><HeartHandshake/><h3>Community reports</h3><p>Submit a concern to the local API. Reports are not yet durable or displayed as verified hotspots.</p></article></div></section><div className="notice section"><strong>A thoughtful guide, not a guarantee.</strong> Conditions can change quickly. Use your judgment and contact local emergency services when in immediate danger.</div></div>}
