"use client";
import {useEffect,useState} from "react";
import {Building2,Clock3,Hospital,Phone,Plus,Train,Trash2} from "lucide-react";
import {fetchSafePlaces} from "@/lib/api";
import {googleMapsDirections} from "@/lib/maps";
import type {Coordinate,SafePlaceResults} from "@/lib/types";
type Contact={name:string;phone:string};
type Category="hospital"|"police"|"transport";
const contactsKey="lunara-trusted-contacts",timerKey="lunara-check-in-deadline";
const categories:[Category,string,typeof Hospital][]=[["hospital","Hospital",Hospital],["police","Police station",Building2],["transport","Transport hub",Train]];
export default function Safety(){
 const [contacts,setContacts]=useState<Contact[]>([]),[name,setName]=useState(""),[phone,setPhone]=useState(""),[contactError,setContactError]=useState("");
 const [places,setPlaces]=useState<SafePlaceResults|null>(null),[category,setCategory]=useState<Category|null>(null),[location,setLocation]=useState<Coordinate|null>(null),[manual,setManual]=useState(""),[placeError,setPlaceError]=useState(""),[searching,setSearching]=useState(false);
 const [deadline,setDeadline]=useState<number|null>(null),[now,setNow]=useState(0);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;setNow(Date.now());try{const saved=JSON.parse(localStorage.getItem(contactsKey)??"[]");if(Array.isArray(saved))setContacts(saved.filter((item):item is Contact=>typeof item?.name==="string"&&typeof item?.phone==="string"));const savedDeadline=Number(localStorage.getItem(timerKey));if(savedDeadline>0)setDeadline(savedDeadline)}catch{/* Ignore corrupt local storage. */}});const interval=setInterval(()=>setNow(Date.now()),1000);return()=>{active=false;clearInterval(interval)}},[]);
 function saveContacts(next:Contact[]){setContacts(next);localStorage.setItem(contactsKey,JSON.stringify(next))}
 function addContact(){if(!name.trim()||!/^\+?[0-9() .-]{7,20}$/.test(phone.trim())){setContactError("Enter a name and a valid phone number.");return}saveContacts([...contacts,{name:name.trim(),phone:phone.trim()}]);setName("");setPhone("");setContactError("")}
 function setTimer(){const next=Date.now()+30*60_000;localStorage.setItem(timerKey,String(next));setDeadline(next);setNow(Date.now())}
 function cancelTimer(){localStorage.removeItem(timerKey);setDeadline(null)}
 async function search(kind:Category){setCategory(kind);setPlaces(null);setPlaceError("");setSearching(true);try{let point=location;if(manual.trim()){const match=manual.trim().match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/);if(!match)throw new Error("Enter coordinates as latitude, longitude, or clear the field to use browser location.");point={lat:Number(match[1]),lng:Number(match[2])};if(Math.abs(point.lat)>90||Math.abs(point.lng)>180)throw new Error("Coordinates are out of range.")}else if(!point){if(!navigator.geolocation)throw new Error("Geolocation is unavailable. Enter latitude, longitude manually.");point=await new Promise<Coordinate>((resolve,reject)=>navigator.geolocation.getCurrentPosition(position=>resolve({lat:position.coords.latitude,lng:position.coords.longitude}),()=>reject(new Error("Location permission was denied or unavailable. Enter latitude, longitude manually.")),{enableHighAccuracy:true,timeout:15000}));}setLocation(point);setPlaces(await fetchSafePlaces(point,kind))}catch(error){setPlaceError(error instanceof Error?error.message:"Nearby search failed.")}finally{setSearching(false)}}
 const remaining=deadline?Math.max(0,Math.ceil((deadline-now)/1000)):0;
 return <div className="container"><div className="page-head"><div><div className="eyebrow">Safety support</div><h1>Help, close at hand</h1><p className="muted">Search mapped places near your location or contact someone you trust.</p></div></div>
 <div className="feature-grid">{categories.map(([kind,title,Icon])=><article className="card feature" key={kind}><Icon/><h3>{title}</h3><p>Search mapped nearby {title.toLowerCase()} locations.</p><button className="secondary" disabled={searching} onClick={()=>void search(kind)}>Find nearby</button></article>)}</div>
 <section className="card journey-card" style={{marginTop:18}}><h2>Nearby search</h2><p className="muted">Uses your browser location with permission. If denied, enter coordinates manually. OpenStreetMap results may be incomplete; hours and staffing are unverified.</p><div className="field"><label htmlFor="manual-coordinates">Manual location (optional latitude, longitude)</label><input id="manual-coordinates" value={manual} onChange={event=>setManual(event.target.value)} placeholder="17.411568, 78.527463"/></div>{searching&&<p role="status">Searching nearby mapped places…</p>}{placeError&&<p role="alert" className="notice">{placeError}</p>}{places&&<><p className="muted">{places.data_status}. Source: {places.source}.</p>{places.places.length===0&&<p>No mapped {category} locations found within 5 km.</p>}{places.places.map(place=><div className="status-row" key={place.id}><span><strong>{place.name}</strong><br/><small>{(place.distance_m/1000).toFixed(1)} km away · <a href={place.osm_url} target="_blank" rel="noopener noreferrer">OpenStreetMap</a></small></span>{location&&<a className="secondary" href={googleMapsDirections(location,place.location)} target="_blank" rel="noopener noreferrer">Navigate</a>}</div>)}</>}</section>
 <section className="card journey-card" style={{marginTop:18}}><h2>Trusted contacts</h2><p className="muted">Stored only in this browser. No cloud sync or automatic alerts.</p><div className="field-row"><div className="field"><label htmlFor="contact-name">Contact name</label><input id="contact-name" value={name} onChange={event=>setName(event.target.value)} placeholder="e.g. Asha"/></div><div className="field"><label htmlFor="contact-phone">Phone number</label><input id="contact-phone" type="tel" value={phone} onChange={event=>setPhone(event.target.value)} placeholder="+91 9876543210"/></div><button className="secondary" onClick={addContact}><Plus/> Add contact</button></div>{contactError&&<p role="alert">{contactError}</p>}{contacts.map((contact,index)=><div className="status-row" key={`${contact.phone}-${index}`}><span>{contact.name}<br/><small>{contact.phone}</small></span><span className="safety-actions"><a className="secondary" href={`tel:${contact.phone.replace(/[^+\d]/g,"")}`}><Phone size={15}/> Call</a><button className="secondary" aria-label={`Remove ${contact.name}`} onClick={()=>saveContacts(contacts.filter((_,i)=>i!==index))}><Trash2 size={15}/></button></span></div>)}</section>
 <section className="card journey-card" style={{marginTop:18}}><Clock3/><h3>Check-in timer</h3><p className="muted">A reminder while this page is open. It does not notify contacts or authorities and cannot be relied upon in the background.</p>{deadline&&<p role={remaining===0?"alert":"timer"}>{remaining===0?"Check-in overdue — please contact someone you trust.":`Check in within ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,"0")}`}</p>}<div className="safety-actions"><button className="secondary" onClick={setTimer}>{deadline?"Reset to 30 minutes":"Set check-in for 30 minutes"}</button>{deadline&&<button className="secondary" onClick={cancelTimer}>{remaining===0?"Checked in / dismiss":"Cancel timer"}</button>}</div></section></div>
}
