import {spawn} from "node:child_process";
import {mkdtempSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
const chrome=spawn("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",["--headless=new","--disable-gpu","--no-first-run","--remote-debugging-port=9243",`--user-data-dir=${mkdtempSync(join(tmpdir(),"lunara-picker-"))}`],{stdio:"ignore",windowsHide:true});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
let socket;
try{
 let page;for(let i=0;i<70;i++){try{const r=await fetch("http://127.0.0.1:9243/json/new?http://localhost:3000/",{method:"PUT"});if(r.ok){page=await r.json();break}}catch{}await delay(200)}if(!page)throw Error("Chrome failed");
 socket=new WebSocket(page.webSocketDebuggerUrl);await new Promise(r=>socket.addEventListener("open",r,{once:true}));
 let id=0;const pending=new Map();socket.addEventListener("message",e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}});const cmd=(method,params={})=>new Promise(r=>{const n=++id;pending.set(n,r);socket.send(JSON.stringify({id:n,method,params}))});
 const evalJs=async code=>(await cmd("Runtime.evaluate",{expression:code,returnByValue:true})).result?.result?.value;
 const until=async code=>{for(let i=0;i<100;i++){const value=await evalJs(code);if(value)return value;await delay(500)}throw Error("Timed out "+code)};
 const click=css=>evalJs(`document.querySelector(${JSON.stringify(css)})?.click()`);
 const type=(css,value)=>evalJs(`(()=>{const e=document.querySelector(${JSON.stringify(css)});if(!e)return;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}))})()`);
 await cmd("Browser.grantPermissions",{permissions:["geolocation"],origin:"http://localhost:3000"});await cmd("Emulation.setGeolocationOverride",{latitude:17.411568,longitude:78.527463,accuracy:10});
 async function pick(kind,search,match){for(let i=0;i<8;i++){await click(`[aria-label="Choose ${kind} on map"]`);if(await evalJs("!!document.querySelector('#picker-query')"))break;await delay(1000)}await until("!!document.querySelector('#picker-query')");await type("#picker-query",search);await until(`[...document.querySelectorAll('.picker-suggestions button')].some(e=>e.innerText.includes(${JSON.stringify(match)}))`);await evalJs(`[...document.querySelectorAll('.picker-suggestions button')].find(e=>e.innerText.includes(${JSON.stringify(match)}))?.click()`);await until("!!document.querySelector('.picker-actions .primary:not(:disabled)')");const address=await evalJs("document.querySelector('.picker-selection')?.innerText");await click(".picker-actions .primary");await until("!document.querySelector('.picker-panel')");return address}
 async function run(mapOrigin){await cmd("Page.navigate",{url:"http://localhost:3000/"});await until("!!document.querySelector('#to')");await delay(1000);const a=mapOrigin?await pick("origin","Osmania University, Hyderabad","Osmania University"):null;const b=await pick("destination",mapOrigin?"LB Nagar, Hyderabad":"Secunderabad Railway Station, Hyderabad",mapOrigin?"LB Nagar":"Secunderabad Junction");const fields=await evalJs("({from:document.querySelector('#from').value,to:document.querySelector('#to').value})");await click("form.search-card button.primary");await until("location.pathname==='/routes'");const params=await evalJs("Object.fromEntries(new URL(location.href).searchParams)");await until("document.querySelectorAll('.route-card').length===3||!!document.querySelector('[role=alert]')");const result=await evalJs("({cards:document.querySelectorAll('.route-card').length,header:document.querySelector('.map-route-header')?.innerText,alert:document.querySelector('[role=alert]')?.innerText,demo:document.body.innerText.includes('DEMO DATA')})");return {a,b,fields,params,result}}
 const a=await run(false),b=await run(true);await cmd("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:1,mobile:true});await cmd("Page.navigate",{url:"http://localhost:3000/"});await until("!!document.querySelector('.hero')");await delay(1000);const mobile=await evalJs("({overflow:document.documentElement.scrollWidth>innerWidth,hero:document.querySelector('.hero').getBoundingClientRect().toJSON(),search:document.querySelector('.search-card').getBoundingClientRect().toJSON()})");console.log(JSON.stringify({a,b,mobile}));if(a.result.cards!==3||b.result.cards!==3||a.result.demo||b.result.demo||a.fields.from!=="Current location"||!a.params.destination_label?.includes("Secunderabad")||!b.params.origin_label?.includes("Osmania")||!b.params.destination_label?.includes("LB Nagar")||mobile.overflow||mobile.search.y<=mobile.hero.y)process.exitCode=1;
}finally{socket?.close();chrome.kill()}
