"use client";
import {useState} from "react";
import {CheckCircle2,MapPin} from "lucide-react";
import {submitReport} from "@/lib/api";

const categories=["Stalking","Harassment","Suspicious following","Verbal harassment","Unsafe transport location","Poor lighting","Isolated road","Suspicious activity","Infrastructure problem","Other safety concern"];
export default function ReportPage(){
  const[category,setCategory]=useState(categories[0]);const[severity,setSeverity]=useState(2);const[description,setDescription]=useState("");
  const[coords,setCoords]=useState<{latitude:number;longitude:number}|null>(null);const[done,setDone]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  function locate(){navigator.geolocation?.getCurrentPosition(p=>{setCoords({latitude:p.coords.latitude,longitude:p.coords.longitude});setError("")},()=>setError("Location permission is needed to submit a report."))}
  async function submit(e:React.FormEvent){e.preventDefault();if(!coords){setError("Add your approximate location first.");return}setBusy(true);setError("");try{await submitReport({category:category.toLowerCase().replaceAll(" ","_"),severity,description,occurred_at:new Date().toISOString(),...coords});setDone(true)}catch{setError("Report was not sent. The reporting service is unavailable; please try again later.")}finally{setBusy(false)}}
  return <div className="container form-page"><div className="page-head"><div><div className="eyebrow">Community safety</div><h1>Report a concern</h1><p className="muted">Share only what is necessary. Your identity is not displayed publicly.</p></div></div>{done?<div className="success"><CheckCircle2/><h3>Report received</h3><p>It will remain pending while reliability signals and community verification are assessed.</p><button className="secondary" onClick={()=>setDone(false)}>Submit another</button></div>:<form className="card" onSubmit={submit}><fieldset style={{border:0,padding:0}}><legend style={{fontWeight:700,marginBottom:10}}>What happened?</legend><div className="chips">{categories.map(c=><button type="button" key={c} className={`chip ${category===c?"active":""}`} onClick={()=>setCategory(c)}>{c}</button>)}</div></fieldset><div className="field"><label htmlFor="severity">Severity: {severity} / 5</label><input id="severity" className="range" type="range" min="1" max="5" value={severity} onChange={e=>setSeverity(+e.target.value)}/></div><div className="field"><label htmlFor="details">Optional details</label><textarea id="details" maxLength={500} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Avoid names or identifying details."/><small className="muted">{description.length}/500</small></div><div className="field"><label>Approximate location</label><button className="secondary" type="button" onClick={locate}><MapPin size={16}/> Use current location</button><small className="muted">{coords?"Location added. Your browser may provide precise coordinates to the service.":"No location selected."}</small></div>{error&&<p role="alert" className="notice">{error}</p>}<button className="primary" disabled={busy}>{busy?"Submitting…":"Submit privately"}</button></form>}</div>
}
