"use client";
import {useEffect,useRef,useState} from "react";
import {MapPin,X} from "lucide-react";
import type {Map as MapLibreMap,Marker as MapLibreMarker} from "maplibre-gl";
import {reversePlace,searchPlaces} from "@/lib/api";
import type {Coordinate,PlaceSuggestion} from "@/lib/types";

type Props={kind:"origin"|"destination";initial?:Coordinate|null;onClose:()=>void;onSelect:(place:PlaceSuggestion)=>void};
export function LocationPicker({kind,initial,onClose,onSelect}:Props){
 const container=useRef<HTMLDivElement>(null),map=useRef<MapLibreMap|null>(null),pin=useRef<MapLibreMarker|null>(null),current=useRef<MapLibreMarker|null>(null),requestId=useRef(0);
 const [point,setPoint]=useState<Coordinate|null>(initial??null),[place,setPlace]=useState<PlaceSuggestion|null>(null),[error,setError]=useState(""),[resolving,setResolving]=useState(false);
 const [query,setQuery]=useState(""),[suggestions,setSuggestions]=useState<PlaceSuggestion[]>([]),[searching,setSearching]=useState(false),[searched,setSearched]=useState(false);
 async function selectPoint(next:Coordinate){const id=++requestId.current;setPoint(next);setPlace(null);setError("");setResolving(true);try{const result=await reversePlace(next);if(id===requestId.current)setPlace(result)}catch(reason){if(id===requestId.current){setError(reason instanceof Error?reason.message:"Address lookup failed.");setPlace({name:"Selected map point",address:"Readable address unavailable; routing will use the selected coordinates.",location:next})}}finally{if(id===requestId.current)setResolving(false)}}
 useEffect(()=>{let cancelled=false;let instance:MapLibreMap|null=null;let ownPin:MapLibreMarker|null=null;let ownCurrent:MapLibreMarker|null=null;import("maplibre-gl").then(ml=>{if(cancelled||!container.current)return;instance=new ml.Map({container:container.current,style:process.env.NEXT_PUBLIC_MAP_STYLE??"https://demotiles.maplibre.org/style.json",center:initial?[initial.lng,initial.lat]:[78.4867,17.3850],zoom:initial?14:11});map.current=instance;instance.addControl(new ml.NavigationControl({showCompass:false}),"top-right");const choose=(next:Coordinate)=>{ownPin?.setLngLat([next.lng,next.lat]);if(!ownPin){ownPin=new ml.Marker({color:"#5c437d",draggable:true}).setLngLat([next.lng,next.lat]).addTo(instance!);pin.current=ownPin;ownPin.on("dragend",()=>{const pos=ownPin!.getLngLat();void selectPoint({lat:pos.lat,lng:pos.lng})})}void selectPoint(next)};instance.on("click",event=>choose({lat:event.lngLat.lat,lng:event.lngLat.lng}));if(initial)choose(initial);if(navigator.geolocation)navigator.geolocation.getCurrentPosition(({coords})=>{if(cancelled||!instance)return;const pos={lat:coords.latitude,lng:coords.longitude};const dot=document.createElement("span");dot.className="picker-current-dot";dot.setAttribute("title","My Current Location");ownCurrent=new ml.Marker({element:dot}).setLngLat([pos.lng,pos.lat]).addTo(instance);current.current=ownCurrent;if(!initial)instance.flyTo({center:[pos.lng,pos.lat],zoom:13})},()=>{/* Permission is optional. */},{timeout:7000})}).catch(()=>{if(!cancelled)setError("Map could not load. Type a place in the search field instead.")});return()=>{cancelled=true;ownPin?.remove();ownCurrent?.remove();instance?.remove();map.current=null;pin.current=null;current.current=null}},[initial]);
 useEffect(()=>{if(query.trim().length<3){queueMicrotask(()=>{setSuggestions([]);setSearched(false)});return}let active=true;const timer=setTimeout(()=>{void(async()=>{setSearching(true);try{const result=await searchPlaces(query.trim());if(active){setSuggestions(result);setSearched(true)}}catch(reason){if(active)setError(reason instanceof Error?reason.message:"Place search failed.")}finally{if(active)setSearching(false)}})()},450);return()=>{active=false;clearTimeout(timer)}},[query]);
 function chooseSuggestion(suggestion:PlaceSuggestion){requestId.current++;setPlace(suggestion);setPoint(suggestion.location);setSuggestions([]);setQuery(suggestion.name);setError("");pin.current?.setLngLat([suggestion.location.lng,suggestion.location.lat]);if(!pin.current&&map.current){import("maplibre-gl").then(ml=>{if(!map.current)return;const marker=new ml.Marker({color:"#5c437d",draggable:true}).setLngLat([suggestion.location.lng,suggestion.location.lat]).addTo(map.current);marker.on("dragend",()=>{const pos=marker.getLngLat();void selectPoint({lat:pos.lat,lng:pos.lng})});pin.current=marker})}map.current?.flyTo({center:[suggestion.location.lng,suggestion.location.lat],zoom:15})}
 return <div className="picker-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="picker-panel" role="dialog" aria-modal="true" aria-label={`Choose ${kind} on map`}><div className="picker-heading"><div><div className="eyebrow">Lunara map picker</div><h2>Choose {kind} on map</h2></div><button className="picker-close" aria-label="Close map picker" onClick={onClose}><X/></button></div><div className="picker-search"><label htmlFor="picker-query">Search for a place or address</label><input id="picker-query" value={query} onChange={event=>setQuery(event.target.value)} placeholder="e.g. Secunderabad Railway Station" autoComplete="off"/>{searching&&<small role="status">Searching places…</small>}{searched&&!searching&&!suggestions.length&&<small>No results found</small>}{suggestions.length>0&&<ul className="picker-suggestions">{suggestions.map((item,index)=><li key={index}><button onClick={()=>chooseSuggestion(item)}><strong>{item.name}</strong><small>{item.address}</small></button></li>)}</ul>}</div><div ref={container} className="picker-map" aria-label="Interactive OpenStreetMap location picker"/><p className="picker-hint">Tap the map or drag the purple pin to refine the location. The blue dot is your current location when permitted.</p><div className="picker-selection"><MapPin size={20}/><div>{resolving?<strong>Finding address…</strong>:place?<><strong>{place.name}</strong><span>{place.address}</span><small>{point?.lat.toFixed(6)}, {point?.lng.toFixed(6)}</small></>:<span>Select a point or search for a place.</span>}{error&&<small role="alert">{error}</small>}</div></div><div className="picker-actions">{point&&<a className="secondary" href={`https://www.google.com/maps/search/?api=1&query=${point.lat}%2C${point.lng}`} target="_blank" rel="noopener noreferrer">Open in Google Maps</a>}<button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!place||resolving} onClick={()=>{if(place)onSelect(place)}}>Use this location</button></div><small>Google Maps opens separately; external selections do not return to Lunara.</small></section></div>
}
